### ISSUE TITLE
🐛 [Bug]- K8s: failed to render: render: template 404 does not exist

### ISSUE THREAD

**Issue by vuisme** [shurco/litecart#162]
### Bug Description

Can't access to frontend UI, but admin frontend is ok

admin
![image](https://github.com/user-attachments/assets/477a0607-0aa1-4149-8f68-8c58b95394ac)

home
![image](https://github.com/user-attachments/assets/f3e17ea1-708c-49ce-b14c-a207688e3a6a)

### How to Reproduce

I installed on my k3s cluster by this deployment:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecart-pvc
  namespace: shop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-sg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litecart
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litecart
  template:
    metadata:
      labels:
        app: litecart
    spec:
      nodeSelector:
        type: sg
      containers:
      - name: litecart
        image: shurco/litecart:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: litecart-storage
          mountPath: /lc_base
        - name: litecart-storage
          mountPath: /lc_digitals
        - name: litecart-storage
          mountPath: /lc_uploads
        - name: litecart-storage
          mountPath: /site
      volumes:
      - name: litecart-storage
        persistentVolumeClaim:
          claimName: litecart-pvc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litecart-ingress
  namespace: shop
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mydomain
    secretName: litecart-tls
  rules:
  - host: mydomain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: litecart-service
            port:
              number: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: litecart-service
  namespace: shop
spec:
  selector:
    app: litecart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

```
After install and database migration. I can access admin UI by mydomain.com/_/ and everything work well. But when access to home frontend it's throw error:
```
failed to render: render: template 404 does not exist
```

### Expected Behavior

I don't know

### litecart Version

v0.1.12

### Code Snippet (optional)

```go
package main

import "fmt"

func main() {
  fmt.Print("hello word")
}
```

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by shurco** [comment]
Unfortunately, I haven't tested it on k8s and won't be able to do so in the near future. 
I'll add a tag for `hacktoberfest` and hope that there are people who can help check this issue.

**Comment by vuisme** [comment]
This is log of litecart pod.
[litecart.txt](https://github.com/user-attachments/files/17295482/litecart.txt)

**Comment by shurco** [comment]
Do you have a /site folder in the root of the project? What files are in it?

**Comment by vuisme** [comment]
Problem solved. I declared the mount volume values ​​wrong. Sorry. Here is the correct manifest:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecart-pvc
  namespace: shop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-sg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litecart
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litecart
  template:
    metadata:
      labels:
        app: litecart
    spec:
      nodeSelector:
        type: sg
      containers:
      - name: litecart
        image: shurco/litecart:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: litecart-storage
          mountPath: /lc_base
          subPath: lc_base 
        - name: litecart-storage
          mountPath: /lc_digitals
          subPath: lc_digitals
        - name: litecart-storage
          mountPath: /lc_uploads
          subPath: lc_uploads
        - name: litecart-storage
          mountPath: /site
          subPath: site
      volumes:
      - name: litecart-storage
        persistentVolumeClaim:
          claimName: litecart-pvc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litecart-ingress
  namespace: shop
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - domain
    secretName: litecart-tls
  rules:
  - host: domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: litecart-service
            port:
              number: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: litecart-service
  namespace: shop
spec:
  selector:
    app: litecart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
```
